---
format:
  html:
    embed-resources: true
---
```{r}
    rm(list = ls())
```

```{r}
#| message: false
    library(dplyr)
    library("tidyverse")
```

```{r}
#| message: false
diabetes_data <- read_tsv(file = "../data/04_diabetes_data_augment.tsv", na = 'NA')
```

```{r}
plot1 <- ggplot(diabetes_data |>
                  mutate(income = factor(income, levels = c('[0,5000)','[5000,10000)','[10000,15000)','[15000,20000)','[20000,25000)',
                          '[25000,35000)','[35000,45000)','[45000,55000)','[55000,65000)','[65000,75000)','[75000,100000)'))) |>
                  filter(!is.na(income)) |>
                  group_by(income) |>
                  summarize(percentage = sum(diagnosis == 1)*100 / n()),
                aes(x = income,
                    y = percentage,
                    alpha = percentage)
        ) +
        geom_bar(
          stat="identity",
          color="black",
          fill='wheat',
          show.legend=FALSE
        ) +
        scale_alpha_continuous(range = c(0.2, 0.8)) +
        theme(
          text = element_text(size=10),
          axis.text.x = element_text(angle = 15, vjust = 1, hjust=1)
        ) +
        coord_cartesian(ylim = c(0, 100)) +
        labs(
          title = "Diabete-diagnosed people vs Family income classes",
          x = "Income classes",
          y = "% of diabete-diagnosed",
          caption = "To be read: within the class of income X, Y% of individuals got diagnosed with diabete."
        )


plot1
```
```{r}
plot1 <- ggplot(diabetes_data |>
dplyr::select(income,
diagnosis) |>
drop_na() |>
group_by(income) |>
summarize(percentage = sum(diagnosis == 1)*100 / n()),
                aes(x = income,
                    y = percentage,
                    alpha = percentage)
        ) +
        geom_bar(
          stat="identity",
          color="black",
          fill='wheat',
          show.legend=FALSE
        ) +
        scale_alpha_continuous(range = c(0.2, 0.8)) +
        theme(
          text = element_text(size=10),
          axis.text.x = element_text(angle = 15, vjust = 1, hjust=1)
        ) +
        coord_cartesian(ylim = c(0, 100)) +
        labs(
          title = "Diabete-diagnosed people vs Family income classes",
          x = "Income classes",
          y = "% of diabete-diagnosed",
          caption = "To be read: within the class of income X, Y% of individuals got diagnosed with diabete."
        )


plot1
```


```{r}
plot2_data <- diabetes_data |>
                  mutate(income = factor(income, levels = c('[0,5000)','[5000,10000)','[10000,15000)','[15000,20000)','[20000,25000)',
                        '[25000,35000)','[35000,45000)','[45000,55000)','[55000,65000)','[65000,75000)','[75000,100000)'))) |>
                  filter(!is.na(income), diagnosis==1) |>
                  group_by(income) |>
                  summarize(percentage = sum(medication == 1)*100 / n())

plot2 <- ggplot(plot2_data, aes(x = income, y = percentage, alpha = percentage)) +
  geom_bar(stat="identity", color="black", fill='wheat', show.legend=FALSE) +
  scale_alpha_continuous(range = c(0.2, 0.8)) +
  theme(text = element_text(size=10), axis.text.x = element_text(angle = 15, vjust = 1, hjust=1)) +
  coord_cartesian(ylim = c(0, 100)) +
  labs(
    title = "Medicated people vs Family income classes",
    x = "Income classes",
    y = "% of medicated people",
    caption = "To be read: within the class of income X, Y% of (diabete-diagnosed) individuals got medicated."
  )

plot2
```

```{r}
plot3_data <- diabetes_data |>
                  arrange(age) |>
                  group_by(age) |>
                  summarize(percentage = sum(diagnosis == 1)*100 / n())

plot3 <- ggplot(plot3_data, aes(x = age, y = percentage, alpha = percentage)) +
  geom_bar(stat="identity", color="black", fill="wheat", show.legend=FALSE) +
  scale_alpha_continuous(range = c(0.2, 0.8)) +
  scale_x_continuous(breaks = unique(diabetes_data[["age"]])[unique(diabetes_data[["age"]]) %% 2 == 0]) +
  theme(text = element_text(size=10)) +
  coord_cartesian(ylim = c(0, 100)) +
  labs(
    title = "Diagnosed people vs Age",
    x = "Age",
    y = "% of diabete-diagnoses",
    caption = "To be read: within the people of age X, Y% of individuals got diagnosed with diabete."
  )


plot3
```

